Feature/patch travis composer (#36)
* https://github.com/composer/composer/issues/7797

* .

* Delete composer.phar

* fix syntax error, unexpected '$index'

* fix 'SQL‘ not found
coveralls

* Plugin bootstrap Scripts saved args (set -- $saved)

* php composer.phar

* sql info

* bootstrap test

* Test Workflow

wip : Cannot declare class Tableau, because the name is already in use

* HOW to fix issues Error handling upon first tests

* ./test_cake.sh -p <sql-password> -t

* ERROR 1064 (42000) at line 4 in file: 'app/Config/identities.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'if not exists 'test'@'localhost'' at line 1

* Readme

* Remote CI : mysql socket
ERROR 1064 (42000) at line 4 in file: 'app/Config/identities.sql': You 
have an error in your SQL syntax; check the manual that corresponds to 
your MySQL server version for the right syntax to use near 'if not 
exists 'test'@'127.0.0.1'' at line 1

* COLLECT_COVERAGE coveralls
php unit bootstrap

* environment variable

* Documentation

* ./Scripts/bootstrap.sh: line 35: ./app/vendor/bin/phpunit: No such file or directory

* style

* errno : 1054 sqlstate : 42S22 error : Unknown column 'image' in 'field list'
Fatal error: CakePHP core could not be found.  Check the value of 
CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php.  It should point to the 
directory containing your /cake core directory and your /vendors root 
directory. in 
/home/travis/build/b23prodtm/myphpcms/app/bootstrap_phpunit.php on line 
86

* Helper $view links plugin Markdown

Update php_cms -> Index includes fix :
Fatal error: require(): Failed opening required '' 
(include_path='.:/home/travis/.phpenv/versions/5.6.32/share/pear') in 
/home/travis/build/b23prodtm/myphpcms/app/webroot/php_cms/e13/include/SQL.php 
on line 11

* phpunit bootstrap local ok

* test : no coverage

* autoload tests