Developer preview (#46)
* MessageController in sitemap-menu-index as "contactus"
update my schema sql

* push build notification (#29)

* Coverity scan (#31)

* Coverity code scanner
* in Bash environment, String subsitutions are allowed
* Cache PHP Fatal error:  Uncaught CacheException: Cache engine "_cake_core_" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct in /home/travis/build/b23prodtm/myphpcms/lib/Cake/Cache/Cache.php:186

* Coverity scan (#32)

* in Bash environment, String subsitutions are allowed

* Cache PHP Fatal error:  Uncaught CacheException: Cache engine "_cake_core_" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct in /home/travis/build/b23prodtm/myphpcms/lib/Cake/Cache/Cache.php:186

* issue-3

bitbucket.org/b23prodtm/php-cms#3

* composer install
https://book.cakephp.org/2.0/en/installation/advanced-installation.html#create-a-cakephp-project

autoloader fix 
https://book.cakephp.org/2.0/en/installation/advanced-installation.html#installing-composer

* Configure scripts

* Script YaML travis

* Cake CORE Include

* Cms package

Naming
Cake package autoloading

* Helpers

* MySQL 5.7

* Fix Scripts prompt

* a commit

* Bootstrap shell (darwin)

* /TravisCI-OSX-PHP/build/ brew php@version

* use dev branch

* Use https for gitmodules !

$ git submodule deinit .travis/TravisCI-OSX-PHP/
$ git rm .travis/TravisCI-OSX-PHP/
$ git submodule add --force https://github.com/b23prodtm/TravisCI-OSX-PHP.git .travis/TravisCI-OSX-PHP/

* Feature/travis build patch (#30)

* php core travis-ci osx

* $(which cmd) > /dev/null
./configure.sh -Y -Y -Y -N -p pass -s word

* ./configure.sh -c -d -n -h -p pass -s word travis

* mov composer to configure.sh

* Fix Error : Fatal error: Class 'Index' not found in /home/travis/build/b23prodtm/myphpcms/app/View/Helper/InfoHelper.php on line 19 Error: Database connection "Mysql" is missing, or could not be created.

* Up8 plugin Boot args https://github.com/cakephp/debug_kit

* coverage tests

* Feature/patch travis composer (#34)

* https://github.com/composer/composer/issues/7797

* Test Workflow

wip : Cannot declare class Tableau, because the name is already in use

* HOW to fix issues Error handling upon first tests

* ./test_cake.sh -p <sql-password> -t

* ERROR 1064 (42000) at line 4 in file: 'app/Config/identities.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'if not exists 'test'@'localhost'' at line 1

* Readme

* Remote CI : mysql socket
ERROR 1064 (42000) at line 4 in file: 'app/Config/identities.sql': You 
have an error in your SQL syntax; check the manual that corresponds to 
your MySQL server version for the right syntax to use near 'if not 
exists 'test'@'127.0.0.1'' at line 1

* COLLECT_COVERAGE coveralls
php unit bootstrap

* environment variable

* Documentation

* ./Scripts/bootstrap.sh: line 35: ./app/vendor/bin/phpunit: No such file or directory

* style

* errno : 1054 sqlstate : 42S22 error : Unknown column 'image' in 'field list'
Fatal error: CakePHP core could not be found.  Check the value of 
CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php.  It should point to the 
directory containing your /cake core directory and your /vendors root 
directory. in 
/home/travis/build/b23prodtm/myphpcms/app/bootstrap_phpunit.php on line 
86

* Update php_cms

Fatal error: require(): Failed opening required '' (include_path='.:/home/travis/.phpenv/versions/5.6.32/share/pear') in /home/travis/build/b23prodtm/myphpcms/app/webroot/php_cms/e13/include/SQL.php on line 11

* Revert "Feature/patch travis composer (#34)" (#35)

This reverts commit bbdc9f2ea1ce5205f6f8c3e2aead0e7991a26392.

* Feature/patch travis composer (#36)

* https://github.com/composer/composer/issues/7797

* Hotfix/s2i openshift (#38)

* database configuration
user passwords

* autoload.php

* post-commit hook issue
lib/cake/cache/Engine/FileEngine
Cache application directory
Cache long persist
file perms

* Markdown-plugin composer

* Merge branch 'feature/b23prodtm-markdown-patch-1' into openshift-publish

* composer

* Shell Test Script

* --openshift arg

*  How to fix up 'Database connection "Mysql" is missing, or could not be created' ?

* ERROR 1044 (42000) at line 1: Access denied for user 'test'@'localhost' 
to database 'cakephp_test2'

* migrate script and socket

* dollar-star shell

* openshift: no mysql identities to import

* usage of blank password

* 'MysqlCms' in 'app/Model/Datasource/Database'

* coverity_scan branch

* Update .travis.yml

* Hotfix/mysql cms (#40)

* codesniffer

database configuration
user passwords

auto conf
charset settings
1st release

* post-commit hook issue
lib/cake/cache/Engine/FileEngine
Cache application directory
Cache long persist
file perms

* Markdown-plugin composer

* Merge branch 'feature/b23prodtm-markdown-patch-1' into openshift-publish

* Markdown update start test shell script

* Shell Test Script
* VAR: DATABASE_ENGINE DB Model/Datasource/Database

* Entry points scripts, start, test, migrate, echo password status "using password"
* Homepage
* Update .travis.yml (#43)

* Update .travis.yml

``The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
The download failed repeatedly, aborting.
The command "curl -s http://getcomposer.org/installer | php" failed and exited with 1 during .
```
* Automatic build handle (pre-Docker image) (#45)

* make image from dockerfile scratch

* # This is a combination of 7 commits.
# This is the 1st commit message:

WIP docker-compose
https://onoblog.com/cakephp2-docker-scratch/

7.0 off <= composer symphony php version mismatch

* composer, which check

* latest hhvm package

* Docker @ CircleCi

* Clients
mariadb
composer configure

* Local Test scripts
Install guidelines